[package]
cairo-version = "2.1.0"
name = "proof_of_flight"
version = "0.1.0"
# Use the prelude with the less imports as possible
# from corelib.
edition = "2023_10"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = {git = "https://github.com/dojoengine/dojo.git", tag = "v0.6.0-alpha.2"}

[[target.dojo]]
build-external-contracts = [  ]

[tool.dojo.world]
description = "Drone Light Painting on Starknet built using Dojo Engine"
name = "Proof of Flight"

[tool.dojo.env]
rpc_url = "http://localhost:5050"

# Default account for katana with seed = 0
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
world_address = "0x32f96664c85861e672a6ec78ad7c6b4e502c6b40408c2f5c06c1a5bba81dca2"